apiVersion: v1
kind: Pod
metadata:
  name: soat7grupo5-api
  labels:
    app: api 
spec:
  containers:
  - name: api-container
    image: brunobucci/soat7grupo5
    ports:
    - containerPort: 8080
    envFrom:
        - configMapRef: 
            name: api-configmap