services:
  soat7grupo5-mysql:
    image: mysql:8
    volumes:
    - "./database/init.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soat7grupo5
      MYSQL_USER: soat7grupo5
      MYSQL_PASSWORD: soat7grupo5
    ports:
      - 3306:3306

  soat7grupo5-api:
    depends_on:
      - soat7grupo5-mysql
    image: brunobucci/soat7grupo5
    restart: always
    ports:
      - 8080:8080
