apiVersion: v1
kind: Pod
metadata:
  name: soat7grupo5-mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: mysql:8
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
      volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: init-scripts
      configMap:
        name: mysql-init-scripts