apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat7grupo5-api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: brunobucci/soat7grupo5
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: api-configmap
        resources:
          requests:
            cpu: "512m"
            memory: "256Mi"
          limits:
            cpu: "1.2"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /produtos
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 20
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /produtos
            port: 8081
          initialDelaySeconds: 40
          periodSeconds: 20
          failureThreshold: 5
