apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_INIT_DB: c29hdDdncnVwbzU=
  MYSQL_INIT_USER: c29hdDdncnVwbzU=
  MYSQL_INIT_PASSWORD: c29hdDdncnVwbzU=