apiVersion: v1
kind: Pod
metadata:
  name: soat7grupo5-mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: mysql:8
      ports:
        - containerPort: 3306
      envFrom:
          - configMapRef: 
              name: mysql-configmap
      volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
  volumes:
    - name: init-scripts
      configMap:
        name: mysql-configmap
        items:
          - key: init.sql
            path: init.sql
